<Class> ShooterCharacter
+ 0x0670 = <ENUM> CachedTeamColor // size = 1
+ 0x0674 = <Name> CachedTeamTheme // size = 12
+ 0x0680 = <Color> CachedFresnelColor // size = 4
+ 0x0684 = <float> CachedFresnelOffset // size = 4
+ 0x0688 = <float> CachedFresnelIntensity // size = 4
+ 0x068C = <float> CachedLocalFresnelOffset // size = 4
+ 0x0690 = <float> FresnelIntensity // size = 4
+ 0x0694 = <float> FresnelOffset // size = 4
+ 0x0698 = <float> OriginalFresnelIntensity // size = 4
+ 0x069C = <float> OriginalFresnelOffset // size = 4
+ 0x06A0 = <OnCharacterDeathSignature__DelegateSignature> OnCharacterPreDeath // size = 16
+ 0x06B0 = <OnCharacterDeathResponseSignature__DelegateSignature> OnCharacterDeath // size = 16
+ 0x06C0 = <OnCharacterGotKillSignature__DelegateSignature> OnAuthGotKill // size = 16
+ 0x06D0 = <OnCharacterGotKillSignature__DelegateSignature> OnAuthGenerateKillEffects // size = 16
+ 0x06E0 = <OnCharacterTakeDamageSignature__DelegateSignature> OnAuthTookDamage // size = 16
+ 0x0708 = <OnCharacterMovedSignature__DelegateSignature> OnAuthMoved // size = 16
+ 0x0718 = <OnCharacterDamagedCharacterSignature__DelegateSignature> AuthOnDealtDamageToCharacter // size = 16
+ 0x0728 = <OnCharacterUsedEquippableSignature__DelegateSignature> OnAuthUsedEquippable // size = 16
+ 0x0738 = <OnMoveBlockedSignature__DelegateSignature> OnMoveBlocked // size = 16
+ 0x0770 = <OnCharacterSpawnComplete__DelegateSignature> OnCharacterSpawnComplete // size = 16
+ 0x0780 = <bool> bIsPlayerCharacter // size = 1
+ 0x0781 = <bool> bWaitingToNotifyGameState // size = 1
+ 0x0788 = <OnInstigatorChange__DelegateSignature> OnInstigatorChanged // size = 16
+ 0x0798 = <OnPossession__DelegateSignature> OnPossession // size = 16
+ 0x07A8 = <OnPossession__DelegateSignature> OnClientControllerChanged // size = 16
+ 0x07B8 = <OnCameraUpdated__DelegateSignature> OnCameraUpdated // size = 16
+ 0x07C8 = <bool> bAIControlled // size = 1
+ 0x07C9 = <bool> bCreatedWithReuseActorRespawnDisabled // size = 1
+ 0x07CC = <float> TargetEyeHeightProportion // size = 4
+ 0x07D0 = <RoundPersistenceComponent*> Persistence // size = 8
+ 0x07D8 = <GamepadTuningDataAsset*> GamepadTuningData // size = 8
+ 0x07E0 = <AresAbilitySystemComponent*> AbilitiesAndBuffs // size = 8
+ 0x07E8 = <uint8> AuthPrevRemoteRole // size = 1
+ 0x07F0 = <ARRAY> AdditionalTickingComponentWhitelist // size = 16
+ 0x0818 = <ShooterCharacterFogOfWarComponent*> FogOfWarComponent // size = 8
+ 0x0820 = <ShooterCharacterVisionComponent*> VisionComponent // size = 8
+ 0x0828 = <FootstepsComponent*> FootstepsComponent // size = 8
+ 0x0830 = <CalloutRegionTrackingComponent*> CalloutRegionTrackingComponent // size = 8
+ 0x0838 = <DynamicBlockingComponent*> DynamicBlocking // size = 8
+ 0x0888 = <ShooterGameTimeMarker> AuthLastPlayerInputTimestamp // size = 12
+ 0x0898 = <OnTouchStartWidgets__DelegateSignature> OnStartTouchWidgets // size = 16
+ 0x08A8 = <OnTouchStopWidgets__DelegateSignature> OnStopTouchWidgets // size = 16
+ 0x08B8 = <CharacterAbilityWidget*> AbilityHUDWidget // size = 8
+ 0x08C0 = <CLASS> AbilityHUDWidgetTemplate // size = 8
+ 0x08C8 = <AresInputStateComponent*> InputStateComponent // size = 8
+ 0x08D0 = <NetworkStreamComponent*> NetworkStreamComponent // size = 8
+ 0x08D8 = <ARRAY> StartingEquippables // size = 16
+ 0x08E8 = <bool> bCanReceiveModeSpecificInventory // size = 1
+ 0x08F0 = <ARRAY> StartingEquippableClasses // size = 16
+ 0x0900 = <ARRAY> StartingPurchasableAssets // size = 16
+ 0x0910 = <OnCharacterResurrected__DelegateSignature> AuthOnCharacterResurrected // size = 16
+ 0x0920 = <AresInventory*> Inventory // size = 8
+ 0x0940 = <OnResistedDeath__DelegateSignature> AuthOnResistedDeath // size = 16
+ 0x0978 = <DamageableComponent*> DamageHandler // size = 8
+ 0x0980 = <OnFocusProjectileEvent__DelegateSignature> OnFocusProjectileChanged // size = 16
+ 0x0990 = <OnFocusProjectileEvent__DelegateSignature> OnFocusProjectileInvalidated // size = 16
+ 0x09A0 = <ARRAY> FocusProjectiles // size = 16
+ 0x09B0 = <ShooterCharacterDeathReactionComponent*> DeathReactionComponent // size = 8
+ 0x09B8 = <OnCharacterCollisionChanged__DelegateSignature> OnCollisionChangedFromDeath // size = 16
+ 0x09C8 = <CLASS> DeathEffectContainer // size = 8
+ 0x09D0 = <ARRAY> ChannelsToIgnoreWhenIntangible // size = 16
+ 0x09E0 = <uint8> IntangibleObjectType // size = 1
+ 0x09E1 = <CollisionResponseContainer> TangibleCapsuleResponse // size = 32
+ 0x0A01 = <CollisionResponseContainer> TangibleMeshResponse // size = 32
+ 0x0A21 = <CollisionResponseContainer> IntangibleCapsuleResponse // size = 32
+ 0x0A41 = <CollisionResponseContainer> IntangibleMeshResponse // size = 32
+ 0x0A68 = <MAP> AnimationAssociatedEquippables // size = 80
+ 0x0AC0 = <AkAudioEvent*> HitConfirmEvent // size = 8
+ 0x0AC8 = <AkAudioEvent*> HitConfirmHeadshotEvent // size = 8
+ 0x0AD0 = <float> TeamVisionBlindThreshold // size = 4
+ 0x0AD4 = <bool> bCharacterMakesBloodSplatters // size = 1
+ 0x0AD5 = <bool> bCharacterHasNavPointAttached // size = 1
+ 0x0AD8 = <CLASS> NavpointComponentType // size = 8
+ 0x0AE0 = <OnTeamChanged__DelegateSignature> OnTeamChanged // size = 16
+ 0x0AF0 = <OnDeathCameraComplete__DelegateSignature> OnDeathCameraComplete // size = 16
+ 0x0B00 = <float> CameraShakeDamageScalar // size = 4
+ 0x0B08 = <OnUpdateCharacterMeshesSignature__DelegateSignature> OnUpdateCharacterMeshes // size = 16
+ 0x0B18 = <OnPerspectiveChangedSignature__DelegateSignature> OnPerspectiveChanged // size = 16
+ 0x0B28 = <OnCharacterLanded__DelegateSignature> OnCharacterLanded // size = 16
+ 0x0B48 = <OnJumpPressedSignature__DelegateSignature> OnJumpKeyPressed // size = 16
+ 0x0B58 = <OnJumpPressedSignature__DelegateSignature> OnJumpKeyReleased // size = 16
+ 0x0B68 = <ARRAY> CharacterClassSlotModifiers // size = 16
+ 0x0B78 = <ARRAY> CharacterClassCostModifiers // size = 16
+ 0x0B88 = <ARRAY> CharacterClassExcludedPurchasableAssets // size = 16
+ 0x0B98 = <int32> TotalPurchasablesModifier // size = 4
+ 0x0BA0 = <ARRAY> CharacterClassDamageTypeModifiers // size = 16
+ 0x0BB0 = <SkeletalMeshComponent*> Mesh1P // size = 8
+ 0x0BB8 = <SkeletalMeshComponent*> MeshOverlay1P // size = 8
+ 0x0BC0 = <SkeletalMeshComponent*> MeshCosmetic3P // size = 8
+ 0x0BC8 = <bool> WasEquippableWantsToHideFirstPersonMesh // size = 1
+ 0x0BC9 = <bool> WasControllerWantsToHideFirstPersonMesh // size = 1
+ 0x0BCA = <bool> WasInvisible // size = 1
+ 0x0BCB = <bool> WasIntangible // size = 1
+ 0x0BCC = <bool> WasFirstPerson // size = 1
+ 0x0BCD = <bool> WasInvisibleEquippables // size = 1
+ 0x0BCE = <bool> WasInvisible1P // size = 1
+ 0x0BCF = <bool> WasAlly // size = 1
+ 0x0BD0 = <bool> bMeshesDirtyInitiallyComputed // size = 1
+ 0x0BD1 = <bool> bIsLeftHanded // size = 1
+ 0x0C08 = <bool> InitialPossessionOccured // size = 1
+ 0x0C0C = <float> JumpFallDistanceRequiredForLandingSound // size = 4
+ 0x0C10 = <CurveFloat*> JumpFallDamageCurve // size = 8
+ 0x0C18 = <CLASS> JumpFallDamageTypeAsset // size = 8
+ 0x0C20 = <bool> bAlternateMovementHeld // size = 1
+ 0x0C20 = <bool> bCrouchHeld // size = 1
+ 0x0C21 = <bool> bMoveSyncCrouchHeld // size = 1
+ 0x0C22 = <bool> bIsJumpKeyHeld // size = 1
+ 0x0C24 = <float> LastJumpKeyDownTimestamp // size = 4
+ 0x0C28 = <float> MitigatedFallDistance // size = 4
+ 0x0C30 = <ARRAY> Mesh3PMIDs // size = 16
+ 0x0C40 = <ARRAY> Mesh1PMIDs // size = 16
+ 0x0C50 = <ARRAY> Mesh1POverlayMIDs // size = 16
+ 0x0C60 = <CLASS> DropOnDeathObjectTemplateAsset // size = 8
+ 0x0C68 = <bool> bDropObjectWithKillersTeam // size = 1
+ 0x0C70 = <AkAudioEvent*> DeathEvent // size = 8
+ 0x0C78 = <ParticleSystem*> RespawnFX // size = 8
+ 0x0C80 = <AkAudioEvent*> RespawnEvent // size = 8
+ 0x0C88 = <AkAudioEvent*> TargetingEvent // size = 8
+ 0x0C90 = <float> CorpseLifetime // size = 4
+ 0x0CB0 = <float> ServerCosmeticDeathTimestamp // size = 4
+ 0x0CB4 = <float> MinimumTimeBetweenCameraHitRolls // size = 4
+ 0x0CB8 = <float> TimeOfLastCameraHitRoll // size = 4
+ 0x0CBC = <float> AddedEyeHeight // size = 4
+ 0x0CC0 = <float> StandingEyeOffset // size = 4
+ 0x0CC4 = <float> CrouchingEyeOffset // size = 4
+ 0x0CC8 = <OnCausedDamageResponseSignature__DelegateSignature> OnCausedDamageResponse // size = 16
+ 0x0CD8 = <OnFiredProjectilesSignature__DelegateSignature> OnFiredProjectiles // size = 16
+ 0x0CE8 = <OnFiredProjectilesExSignature__DelegateSignature> OnFiredProjectilesEx // size = 16
+ 0x0CF8 = <OnCharacterFallingOutOfWorld__DelegateSignature> OnAuthFallingOutOfWorld // size = 16
+ 0x0D08 = <OnCharacterTeleportedSignature__DelegateSignature> OnTeleported // size = 16
+ 0x0D18 = <ForceModuleManagerComponent*> ForceModuleManager // size = 8
+ 0x0D20 = <StealthComponent*> StealthComponent // size = 8
+ 0x0D28 = <OnInventoryRestoredSignature__DelegateSignature> OnInventoryRestored // size = 16
+ 0x0D38 = <float> MaxShield // size = 4
+ 0x0D3C = <float> MaxOvershield // size = 4
+ 0x0D40 = <float> ShieldDegenerationPerSecond // size = 4
+ 0x0D44 = <float> CrouchTimeSeconds // size = 4
+ 0x0D48 = <float> OverrideCrouchTimeSeconds // size = 4
+ 0x0D4C = <float> CrouchCompressionAmount // size = 4
+ 0x0D50 = <bool> bIsStuckUncrouching // size = 1
+ 0x0D54 = <float> CharacterScale // size = 4
+ 0x0D58 = <CharacterScaleData> CharacterScaleData // size = 24
+ 0x0D70 = <WeakObjectPtr<ShooterCharacter>> ScavengableCharacter // size = 8
+ 0x0D78 = <Rotator> FacingControlRotation // size = 12
+ 0x0D88 = <PurchasableList> CharacterPurchasables // size = 16
+ 0x0D98 = <ARRAY> PurchasableClassAssets // size = 16
+ 0x0DA8 = <int32> NumPointsNeededForUltimate // size = 4
+ 0x0DAC = <int32> DesignPlaytestNumPointsNeededForUltimate // size = 4
+ 0x0DB0 = <ARRAY> HeadDamageBoneNames // size = 16
+ 0x0DC0 = <ARRAY> LegDamageBoneNames // size = 16
+ 0x0DD0 = <uint8> OptimalRange // size = 1
+ 0x0DD4 = <float> AimPunchMovementErrorThreshold // size = 4
+ 0x0DD8 = <MaterialInterface*> Baked3PMaterial // size = 8
+ 0x0DE0 = <MaterialInterface*> Baked1PMaterial // size = 8
+ 0x0DE8 = <bool> bIsTornOff // size = 1
+ 0x0DF0 = <CLASS> DeathReactionTemplateAsset // size = 8
+ 0x0DF8 = <AresHitReactions*> DeathReactionObject // size = 8
+ 0x0E00 = <CLASS> AltDeathReactionTemplateAsset // size = 8
+ 0x0E08 = <AresHitReactions*> AltDeathReactionObject // size = 8
+ 0x0E10 = <float> DeathAwakeTime // size = 4
+ 0x0E18 = <float> DeathClothSettleTime // size = 4
+ 0x0E28 = <OnBecomeViewTarget__DelegateSignature> OnBecomeViewTarget // size = 16
+ 0x0E38 = <OnEndViewTarget__DelegateSignature> OnEndViewTarget // size = 16
+ 0x0E48 = <ParticleSystemComponent*> AllyIconParticleSystem // size = 8
+ 0x0E50 = <Vector> OldCachedLocation // size = 12
+ 0x0E60 = <CombatReportTrackingConfigComponent*> CombatReportTrackingConfig // size = 8
+ 0x0E68 = <ReplicationSleepComponent*> ReplicationSleepComponent // size = 8
+ 0x0E74 = <Ares3PCameraSettings> Camera3PSettings // size = 28
+ 0x0E90 = <Texture*> NonPlayerCharacterIcon // size = 8
+ 0x0E98 = <ENUM> CameraState // size = 1
+ 0x0EA0 = <CameraComponent*> FollowRecoilCameraComponent // size = 8
+ 0x0EA8 = <CameraComponent*> CustomActiveCameraComponent // size = 8
+ 0x0EB0 = <SpringArmComponent*> DeathCameraSpringArm // size = 8
+ 0x0EB8 = <CameraComponent*> DeathCameraComponent // size = 8
+ 0x0EC0 = <ENUM> DebugCameraMode // size = 1
+ 0x0EC8 = <AresDeathCameraSettings> DeathCameraSettings // size = 64
+ 0x0F5C = <WeakObjectPtr<CharacterDataAsset>> DataAsset // size = 8
+ 0x0F88 = <ServerRewindComponent*> ServerRewindComponent // size = 8
+ 0x0F90 = <TransformRewinderComponent*> TransformRewinderComponent // size = 8
+ 0x0F98 = <SkeletalPoseRewinderComponent*> SkeletalPoseRewinderComponent // size = 8
+ 0x0FA1 = <bool> bIsForced1PTextureStreamingEnabled // size = 1
+ 0x0FA4 = <int32> TickOrderId // size = 4
+ 0x0FA8 = <CLASS> DisconnectedBuff // size = 8
+ 0x0FB0 = <OnDisconnectedCharacterDestroyed__DelegateSignature> OnDisconnectedCharacterDestroyed // size = 16
+ 0x0FC0 = <float> GamepadBaseTurnRate // size = 4
+ 0x0FC4 = <float> GamepadBaseLookUpRate // size = 4
+ 0x0FD8 = <int32> NumResetsForRespawn // size = 4
+ 0x0FE0 = <DeadAndSettledRespawnData> DeadAndSettledRespawnData // size = 4
+ 0x0FE8 = <DefaultSkeletalMeshInfo> Mesh1PDefaultSkeletalMeshInfo // size = 16
+ 0x0FF8 = <DefaultSkeletalMeshInfo> MeshOverlay1PDefaultSkeletalMeshInfo // size = 16
+ 0x1008 = <DefaultSkeletalMeshInfo> MeshCosmetic3PDefaultSkeletalMeshInfo // size = 16
+ 0x1018 = <DefaultSkeletalMeshInfo> CurMeshDefaultSkeletalMeshInfo // size = 16
+ 0x1028 = <ARRAY> DefaultPrimitiveComponents // size = 16